server:
  port: ${port:8811}
#  use-forward-headers: true
#  tomcat:
#    protocol-header: X-FORWARDED-PROTO
#    remote-ip-header: X-FORWARDED-FOR
#    port-header: X-Forwarded-Port
#    max-threads: 100
spring:
#  aop:
#    auto: true
#    proxy-target-class: true
  application:
    name: Microservices
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true
    username: zls
    password: hz123456
    initSize: 20
    minIdle: 20
    maxActive: 100





    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
  
  # buSihhHTqfgjIOUFiHHkZr9L6hDAKk 
  #LTAIIRIeGvIAVpUi
  #threedmax1
  # oss-cn-shanghai.aliyuncs.com
#oss:
#  end-point: oss-cn-shenzhen.aliyuncs.com
#  access-key-id: LTAIpTdiNBRfUzXw
#  access-key-secret: aLF4fujCnU0DWpzJbayGl3QT1hIbyi
#  bucket: three-model
#cs:
#  project-type: saas
#  ftp-path: 127.0.0.1

#logging:
#  path: G:/log/

 
 
